/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import ControlaFuncionario.JPanelCadastroFuncionario;
import ControlaFuncionario.JPanelListaFuncionario;        
import ControleCliente.JPanelCadastroCliente;
import ControleCliente.JPanelConsultaCliente;
import Imagem.JPanel.JPanelImagemGerente;
import java.awt.CardLayout;
import javax.security.auth.callback.ConfirmationCallback;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author ander
 */
public class JFrameGerente extends javax.swing.JFrame {

    /**
     * Creates new form JFrameGerente
     */
    CardLayout card;

    public JFrameGerente() {
        initComponents();
        this.setVisible(true);
        JPanel jPanelImagemGerente = new JPanelImagemGerente();
        card = (CardLayout) jPanelBase.getLayout();
        jPanelBase.add(jPanelImagemGerente);
        card.show(jPanelBase, "jPanelImagemGerente");

        this.setLocationRelativeTo(null);
        this.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelLogo = new javax.swing.JLabel();
        jPanelBase = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFuncionario = new javax.swing.JMenu();
        jMenuItemFuncionarioCadastrar = new javax.swing.JMenuItem();
        jMenuItemFuncionarioConsultar = new javax.swing.JMenuItem();
        jMenuCliente = new javax.swing.JMenu();
        jMenuItemClienteCadastrar = new javax.swing.JMenuItem();
        jMenuItemClienteConsultar = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/redebras-topo-menor.jpg"))); // NOI18N
        jLabelLogo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanelBase.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelBase.setPreferredSize(new java.awt.Dimension(1000, 600));
        jPanelBase.setLayout(new java.awt.CardLayout());

        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jMenuFuncionario.setText("Funcionários");

        jMenuItemFuncionarioCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Icones/add_user.png"))); // NOI18N
        jMenuItemFuncionarioCadastrar.setText("Cadastrar");
        jMenuFuncionario.add(jMenuItemFuncionarioCadastrar);

        jMenuItemFuncionarioConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Icones/find_user.png"))); // NOI18N
        jMenuItemFuncionarioConsultar.setText("Consultar");
        jMenuFuncionario.add(jMenuItemFuncionarioConsultar);

        jMenuBar1.add(jMenuFuncionario);

        jMenuCliente.setText("Clientes");

        jMenuItemClienteCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Icones/add_user.png"))); // NOI18N
        jMenuItemClienteCadastrar.setText("Cadastrar");
        jMenuItemClienteCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClienteCadastrarActionPerformed(evt);
            }
        });
        jMenuCliente.add(jMenuItemClienteCadastrar);

        jMenuItemClienteConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Icones/find_user.png"))); // NOI18N
        jMenuItemClienteConsultar.setText("Consultar");
        jMenuItemClienteConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClienteConsultarActionPerformed(evt);
            }
        });
        jMenuCliente.add(jMenuItemClienteConsultar);

        jMenuBar1.add(jMenuCliente);

        jMenuSair.setText("Sair");
        jMenuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSairMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelLogo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanelBase, javax.swing.GroupLayout.DEFAULT_SIZE, 1341, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelLogo)
                .addGap(18, 18, 18)
                .addComponent(jPanelBase, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSairMouseClicked
        int confirm = JOptionPane.showConfirmDialog(null, "Deseja sair?", "Confirmação", ConfirmationCallback.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuSairMouseClicked

    private void jMenuItemClienteCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClienteCadastrarActionPerformed
        JPanel jPanelCadastroCliente = new JPanelCadastroCliente();
        jPanelBase.add(jPanelCadastroCliente);
        card.next(jPanelBase);
    }//GEN-LAST:event_jMenuItemClienteCadastrarActionPerformed

    private void jMenuItemClienteConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClienteConsultarActionPerformed
        JPanel jPanelConsultaCliente = new JPanelConsultaCliente();
        jPanelBase.add(jPanelConsultaCliente);
        card.next(jPanelBase);
    }//GEN-LAST:event_jMenuItemClienteConsultarActionPerformed

    private void jMenuItemFuncionarioCadastrarActionPerformed(java.awt.event.ActionEvent evt) {                                                          
        JPanel jPanelCadastroFuncionario = new JPanelCadastroFuncionario();
        jPanelBase.add(jPanelCadastroFuncionario);
        card.next(jPanelBase);
    }                                                         

    private void jMenuItemFuncionarioConsultarActionPerformed(java.awt.event.ActionEvent evt) {                                                          
        JPanel jPanelListaFuncionario = new JPanelListaFuncionario();
        jPanelBase.add(jPanelListaFuncionario);
        card.next(jPanelBase);
    }                           
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameGerente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCliente;
    private javax.swing.JMenu jMenuFuncionario;
    private javax.swing.JMenuItem jMenuItemClienteCadastrar;
    private javax.swing.JMenuItem jMenuItemClienteConsultar;
    private javax.swing.JMenuItem jMenuItemFuncionarioCadastrar;
    private javax.swing.JMenuItem jMenuItemFuncionarioConsultar;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JPanel jPanelBase;
    // End of variables declaration//GEN-END:variables
}
